### ISSUE TITLE
Saving sheets containing datetime objects to ods format

### ISSUE THREAD

**Issue by vinraspa** [pyexcel/pyexcel-ods3#27]
Hi,

I am new to pyexcel.
I try to save data to both `xlsx` and `ods` formats.
I have trouble when saving sheets containing `datetime` objects in `ods` format (actually, same problem with `xls`).
Things are OK with `xlsx` format.
See below a MWE and traceback

```
>>> import pyexcel, pyexcel_ods3, datetime
>>> data = [[datetime.datetime(2020, 1,1)]]
>>> sheet = pyexcel.Sheet(data)
>>> sheet.save_as('test.xlsx')           # This one is OK
>>> 
>>> sheet.save_as('test.ods')            # This one fails
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/.../python3.8/site-packages/pyexcel/internal/meta.py", line 260, in save_as
    return save_sheet(self, file_name=filename, **keywords)
  File "/home/.../python3.8/site-packages/pyexcel/internal/core.py", line 48, in save_sheet
    return _save_any(a_source, sheet)
  File "/home/.../python3.8/site-packages/pyexcel/internal/core.py", line 60, in _save_any
    a_source.write_data(instance)
  File "/home/.../python3.8/site-packages/pyexcel/plugins/sources/file_output.py", line 31, in write_data
    self._renderer.render_sheet_to_file(
  File "/home/.../python3.8/site-packages/pyexcel/plugins/renderers/excel.py", line 28, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "/home/.../python3.8/site-packages/pyexcel_io/io.py", line 143, in save_data
    writer.write(to_store)
  File "/home/.../python3.8/site-packages/pyexcel_io/writer.py", line 42, in write
    self.writer.write(incoming_dict)
  File "/home/.../python3.8/site-packages/pyexcel_io/plugin_api/abstract_writer.py", line 12, in write
    sheet_writer.write_array(incoming_dict[sheet_name])
  File "/home/.../python3.8/site-packages/pyexcel_ods3/odsw.py", line 66, in write_array
    self.write_row(row)
  File "/home/.../python3.8/site-packages/pyexcel_ods3/odsw.py", line 38, in write_row
    value_type = service.ODS_WRITE_FORMAT_COVERSION[type(cell)]
KeyError: <class 'datetime.datetime'>
```
Is that a bug or am I missing something?

Why is the key `datetime.datetime` missing from `ODS_WRITE_FORMAT_COVERSION` and the two others?

```
ODS_FORMAT_CONVERSION = {
    "float": float,
    "date": datetime.date,
    "time": datetime.time,
    "timedelta": datetime.timedelta,
    "boolean": bool,
    "percentage": float,
    "currency": float,
}

ODS_WRITE_FORMAT_COVERSION = {
    float: "float",
    int: "float",
    str: "string",
    datetime.date: "date",
    datetime.time: "time",
    datetime.timedelta: "timedelta",
    bool: "boolean",
}

VALUE_CONVERTERS = {
    "float": float_value,
    "date": date_value,
    "time": time_value,
    "timedelta": time_value,
    "boolean": boolean_value,
    "percentage": float_value,
}
```

Thank you.

**Comment by vinraspa** [comment]
I found a way to fix it.

in file `pyexcel_ods3/odsw.py`, in method `ODSSheetWriter.write_row()`, in `for cell in array` loop, add this:
```
            if value_type == 'datetime':
                cell = "%04d-%02d-%02dT%02d:%02d:%02d" % (cell.year, cell.month, cell.day,
                                                          cell.hour, cell.minute, cell.second)
                value_type = "date"
```
in file `pyexcel_io/service.py`, add 
```
    datetime.datetime: "datetime",
```
to `ODS_WRITE_FORMAT_COVERSION` dictionary.

**Comment by chfw** [comment]
Thanks for your PR
