### ISSUE TITLE
Cannot write even a single row using 0.6.0

### ISSUE THREAD

**Issue by ShaheedHaque** [pyexcel/pyexcel-ods3#29]
I'm using the following software:
```
$ sudo -H pip3 list | egrep 'ezodf|ods3'
ezodf                         0.3.2               
pyexcel-ezodf                 0.3.4               
pyexcel-ods3                  0.6.0       
```
I am unable to write even a single row without hitting an exception. Here is a test program:
```
#!/bin/env python3
from pyexcel_io import writer

FILENAME = 'tmp.ods'
LIBRARIES = ['pyexcel-ods', 'pyexcel-ods3', 'pyexcel-odsw']
LIBRARY = LIBRARIES[1]
ROW = ['c' + str(c) for c in range(153)]


with writer.Writer('ods', library=LIBRARY) as file_stream:
    file_stream.open(FILENAME)
    page_stream = file_stream.writer.create_sheet('mysheet')
    page_stream.write_row(ROW)

```
and the exception:
```
$ ./ods.py 
Traceback (most recent call last):
  File "./ods.py", line 13, in <module>
    page_stream.write_row(ROW)
  File "/usr/local/lib/python3.8/dist-packages/pyexcel_ods3/odsw.py", line 50, in write_row
    self.ods_sheet[self.current_row, count].set_value(
  File "/usr/local/lib/python3.8/dist-packages/ezodf/table.py", line 51, in __getitem__
    return self.get_cell(get_cell_index(key))
  File "/usr/local/lib/python3.8/dist-packages/ezodf/table.py", line 110, in get_cell
    return wrap(self._cellmatrix.get_cell(pos))
  File "/usr/local/lib/python3.8/dist-packages/ezodf/tablerowcontroller.py", line 40, in get_cell
    return self._rows[row][col]
  File "src/lxml/etree.pyx", line 1161, in lxml.etree._Element.__getitem__
IndexError: list index out of range
```
At the point of the exception, `row` is 0 and `col` is 10. Have I missed some setup step? Note that the real code for which this is a cut-down reproducer has to support xslx/csv/ods file formats and both xslx/csv seem to work fine.

**Comment by chfw** [comment]
with pyexcel-ods3, it is an odd one. 


#!/bin/env python3
from pyexcel_io import writer

FILENAME = 'tmp.ods'
LIBRARIES = ['pyexcel-ods', 'pyexcel-ods3', 'pyexcel-odsw']
LIBRARY = LIBRARIES[1]
ROW = ['c' + str(c) for c in range(153)]

```
with writer.Writer('ods', library=LIBRARY) as file_stream:
    file_stream.open(FILENAME)
    page_stream = file_stream.writer.create_sheet('mysheet')
    page_stream._set_size((10, 200))  # <--- you need a dimension in advance. if you use pyexcel-ods, you won't need such.
    page_stream.write_row(ROW)
```
